spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.0.0.198/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  port: 8080
wechat:
  mpAppId: wx423bd3ecf446a34b
  mpAppSecret: df01772e81b64268ec43335102a89702
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level:
#    root: info
#    root: error
#    com.kfzx.sell.LoggerTest: info